messages:
  plugin_prefix: "&a{ДИОНИС}"
  sinyak_on: "Искренне поздравляем! Вы стали синяком! Теперь, если вы не употребляете пьянящий напиток раз в 20 минут, то вы будете получать эффект тьмы. Излечиться от этого благородного недуга поможет Винозельце, но его рецепт мы вам не скажем. Ищите его сами!)"
  sinyak_off: "Поздравляем! Даже если вы и не были синяком, то теперь вы точно больше не синяк! Винозельце исцелило вас от зависимости! Радуйтесь жизни!)"